/* 
 * GetMyInvoices API Documentation
 *
 * Documentation for GetMyInvoices API endpoints.
 *
 * OpenAPI spec version: v3
 * Contact: support@getmyinvoices.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Minicon.GetMyInvoices.Client.Model;

/// <summary>
///     AddCustomCompany
/// </summary>
[DataContract]
public sealed class AddCustomCompany : IEquatable<AddCustomCompany>
{
	/// <summary>
	///     Initializes a new instance of the <see cref="AddCustomCompany" /> class.
	/// </summary>
	/// <param name="success">Success.</param>
	/// <param name="companyUid">Company ID.</param>
	/// <param name="name">Name.</param>
	public AddCustomCompany(bool? success = default, int? companyUid = default, string name = default)
	{
		Success = success;
		CompanyUid = companyUid;
		Name = name;
	}

	/// <summary>
	///     Success
	/// </summary>
	/// <value>Success</value>
	[DataMember(Name = "success", EmitDefaultValue = false)]
	public bool? Success { get; set; }

	/// <summary>
	///     Company ID
	/// </summary>
	/// <value>Company ID</value>
	[DataMember(Name = "companyUid", EmitDefaultValue = false)]
	public int? CompanyUid { get; set; }

	/// <summary>
	///     Name
	/// </summary>
	/// <value>Name</value>
	[DataMember(Name = "name", EmitDefaultValue = false)]
	public string Name { get; set; }

	/// <summary>
	///     Returns true if AddCustomCompany instances are equal
	/// </summary>
	/// <param name="input">Instance of AddCustomCompany to be compared</param>
	/// <returns>Boolean</returns>
	public bool Equals(AddCustomCompany input)
	{
		if (input == null)
		{
			return false;
		}

		return
			(
				Success == input.Success ||
				(Success != null &&
				 Success.Equals(input.Success))
			) &&
			(
				CompanyUid == input.CompanyUid ||
				(CompanyUid != null &&
				 CompanyUid.Equals(input.CompanyUid))
			) &&
			(
				Name == input.Name ||
				(Name != null &&
				 Name.Equals(input.Name))
			);
	}

	/// <summary>
	///     Returns the string presentation of the object
	/// </summary>
	/// <returns>String presentation of the object</returns>
	public override string ToString()
	{
		var sb = new StringBuilder();
		sb.Append("class AddCustomCompany {\n");
		sb.Append("  Success: ").Append(Success).Append("\n");
		sb.Append("  CompanyUid: ").Append(CompanyUid).Append("\n");
		sb.Append("  Name: ").Append(Name).Append("\n");
		sb.Append("}\n");
		return sb.ToString();
	}

	/// <summary>
	///     Returns the JSON string presentation of the object
	/// </summary>
	/// <returns>JSON string presentation of the object</returns>
	public string ToJson()
	{
		return JsonConvert.SerializeObject(this, Formatting.Indented);
	}

	/// <summary>
	///     Returns true if objects are equal
	/// </summary>
	/// <param name="input">Object to be compared</param>
	/// <returns>Boolean</returns>
	public override bool Equals(object input)
	{
		return Equals(input as AddCustomCompany);
	}

	/// <summary>
	///     Gets the hash code
	/// </summary>
	/// <returns>Hash code</returns>
	public override int GetHashCode()
	{
		unchecked // Overflow is fine, just wrap
		{
			int hashCode = 41;
			if (Success != null)
			{
				hashCode = hashCode * 59 + Success.GetHashCode();
			}

			if (CompanyUid != null)
			{
				hashCode = hashCode * 59 + CompanyUid.GetHashCode();
			}

			if (Name != null)
			{
				hashCode = hashCode * 59 + Name.GetHashCode();
			}

			return hashCode;
		}
	}
}
