/* 
 * GetMyInvoices API Documentation
 *
 * Documentation for GetMyInvoices API endpoints.
 *
 * OpenAPI spec version: v3
 * Contact: support@getmyinvoices.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Minicon.GetMyInvoices.Client.Model;

/// <summary>
///     GetAttachment
/// </summary>
[DataContract]
public sealed class GetAttachment : IEquatable<GetAttachment>
{
	/// <summary>
	///     Initializes a new instance of the <see cref="GetAttachment" /> class.
	/// </summary>
	/// <param name="metaData">metaData.</param>
	/// <param name="fileContent">File Content.</param>
	public GetAttachment(GetAttachmentMetaData metaData = default, string fileContent = default)
	{
		MetaData = metaData;
		FileContent = fileContent;
	}

	/// <summary>
	///     Gets or Sets MetaData
	/// </summary>
	[DataMember(Name = "meta_data", EmitDefaultValue = false)]
	public GetAttachmentMetaData MetaData { get; set; }

	/// <summary>
	///     File Content
	/// </summary>
	/// <value>File Content</value>
	[DataMember(Name = "fileContent", EmitDefaultValue = false)]
	public string FileContent { get; set; }

	/// <summary>
	///     Returns true if GetAttachment instances are equal
	/// </summary>
	/// <param name="input">Instance of GetAttachment to be compared</param>
	/// <returns>Boolean</returns>
	public bool Equals(GetAttachment input)
	{
		if (input == null)
		{
			return false;
		}

		return
			(
				MetaData == input.MetaData ||
				(MetaData != null &&
				 MetaData.Equals(input.MetaData))
			) &&
			(
				FileContent == input.FileContent ||
				(FileContent != null &&
				 FileContent.Equals(input.FileContent))
			);
	}

	/// <summary>
	///     Returns the string presentation of the object
	/// </summary>
	/// <returns>String presentation of the object</returns>
	public override string ToString()
	{
		var sb = new StringBuilder();
		sb.Append("class GetAttachment {\n");
		sb.Append("  MetaData: ").Append(MetaData).Append("\n");
		sb.Append("  FileContent: ").Append(FileContent).Append("\n");
		sb.Append("}\n");
		return sb.ToString();
	}

	/// <summary>
	///     Returns the JSON string presentation of the object
	/// </summary>
	/// <returns>JSON string presentation of the object</returns>
	public string ToJson()
	{
		return JsonConvert.SerializeObject(this, Formatting.Indented);
	}

	/// <summary>
	///     Returns true if objects are equal
	/// </summary>
	/// <param name="input">Object to be compared</param>
	/// <returns>Boolean</returns>
	public override bool Equals(object input)
	{
		return Equals(input as GetAttachment);
	}

	/// <summary>
	///     Gets the hash code
	/// </summary>
	/// <returns>Hash code</returns>
	public override int GetHashCode()
	{
		unchecked // Overflow is fine, just wrap
		{
			int hashCode = 41;
			if (MetaData != null)
			{
				hashCode = hashCode * 59 + MetaData.GetHashCode();
			}

			if (FileContent != null)
			{
				hashCode = hashCode * 59 + FileContent.GetHashCode();
			}

			return hashCode;
		}
	}
}
