/* 
 * GetMyInvoices API Documentation
 *
 * Documentation for GetMyInvoices API endpoints.
 *
 * OpenAPI spec version: v3
 * Contact: support@getmyinvoices.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Minicon.GetMyInvoices.Client.Model;

/// <summary>
///     GetCurrenciesItem
/// </summary>
[DataContract]
public sealed class GetCurrenciesItem : IEquatable<GetCurrenciesItem>
{
	/// <summary>
	///     Initializes a new instance of the <see cref="GetCurrenciesItem" /> class.
	/// </summary>
	/// <param name="name">Name.</param>
	/// <param name="currencyCode">Currency Code.</param>
	public GetCurrenciesItem(string name = default, string currencyCode = default)
	{
		Name = name;
		CurrencyCode = currencyCode;
	}

	/// <summary>
	///     Name
	/// </summary>
	/// <value>Name</value>
	[DataMember(Name = "name", EmitDefaultValue = false)]
	public string Name { get; set; }

	/// <summary>
	///     Currency Code
	/// </summary>
	/// <value>Currency Code</value>
	[DataMember(Name = "currencyCode", EmitDefaultValue = false)]
	public string CurrencyCode { get; set; }

	/// <summary>
	///     Returns true if GetCurrenciesItem instances are equal
	/// </summary>
	/// <param name="input">Instance of GetCurrenciesItem to be compared</param>
	/// <returns>Boolean</returns>
	public bool Equals(GetCurrenciesItem input)
	{
		if (input == null)
		{
			return false;
		}

		return
			(
				Name == input.Name ||
				(Name != null &&
				 Name.Equals(input.Name))
			) &&
			(
				CurrencyCode == input.CurrencyCode ||
				(CurrencyCode != null &&
				 CurrencyCode.Equals(input.CurrencyCode))
			);
	}

	/// <summary>
	///     Returns the string presentation of the object
	/// </summary>
	/// <returns>String presentation of the object</returns>
	public override string ToString()
	{
		var sb = new StringBuilder();
		sb.Append("class GetCurrenciesItem {\n");
		sb.Append("  Name: ").Append(Name).Append("\n");
		sb.Append("  CurrencyCode: ").Append(CurrencyCode).Append("\n");
		sb.Append("}\n");
		return sb.ToString();
	}

	/// <summary>
	///     Returns the JSON string presentation of the object
	/// </summary>
	/// <returns>JSON string presentation of the object</returns>
	public string ToJson()
	{
		return JsonConvert.SerializeObject(this, Formatting.Indented);
	}

	/// <summary>
	///     Returns true if objects are equal
	/// </summary>
	/// <param name="input">Object to be compared</param>
	/// <returns>Boolean</returns>
	public override bool Equals(object input)
	{
		return Equals(input as GetCurrenciesItem);
	}

	/// <summary>
	///     Gets the hash code
	/// </summary>
	/// <returns>Hash code</returns>
	public override int GetHashCode()
	{
		unchecked // Overflow is fine, just wrap
		{
			int hashCode = 41;
			if (Name != null)
			{
				hashCode = hashCode * 59 + Name.GetHashCode();
			}

			if (CurrencyCode != null)
			{
				hashCode = hashCode * 59 + CurrencyCode.GetHashCode();
			}

			return hashCode;
		}
	}
}
