/* 
 * GetMyInvoices API Documentation
 *
 * Documentation for GetMyInvoices API endpoints.
 *
 * OpenAPI spec version: v3
 * Contact: support@getmyinvoices.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Minicon.GetMyInvoices.Client.Model;

/// <summary>
///     GetCurrencies
/// </summary>
[DataContract]
public class GetCurrencies : List<GetCurrenciesItem>, IEquatable<GetCurrencies>
{
	/// <summary>
	///     Initializes a new instance of the <see cref="GetCurrencies" /> class.
	/// </summary>
	public GetCurrencies()
	{
	}

	/// <summary>
	///     Returns true if GetCurrencies instances are equal
	/// </summary>
	/// <param name="input">Instance of GetCurrencies to be compared</param>
	/// <returns>Boolean</returns>
	public bool Equals(GetCurrencies input)
	{
		if (input == null)
		{
			return false;
		}

		return base.Equals(input);
	}

	/// <summary>
	///     Returns the string presentation of the object
	/// </summary>
	/// <returns>String presentation of the object</returns>
	public override string ToString()
	{
		var sb = new StringBuilder();
		sb.Append("class GetCurrencies {\n");
		sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
		sb.Append("}\n");
		return sb.ToString();
	}

	/// <summary>
	///     Returns the JSON string presentation of the object
	/// </summary>
	/// <returns>JSON string presentation of the object</returns>
	public string ToJson()
	{
		return JsonConvert.SerializeObject(this, Formatting.Indented);
	}

	/// <summary>
	///     Returns true if objects are equal
	/// </summary>
	/// <param name="input">Object to be compared</param>
	/// <returns>Boolean</returns>
	public override bool Equals(object input)
	{
		return Equals(input as GetCurrencies);
	}

	/// <summary>
	///     Gets the hash code
	/// </summary>
	/// <returns>Hash code</returns>
	public override int GetHashCode()
	{
		int hashCode = base.GetHashCode();
		return hashCode;
	}
}
