/* 
 * GetMyInvoices API Documentation
 *
 * Documentation for GetMyInvoices API endpoints.
 *
 * OpenAPI spec version: v3
 * Contact: support@getmyinvoices.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Minicon.GetMyInvoices.Client.Model;

/// <summary>
///     GetDocumentMetaDataWorkflowDetailsCurrentWorkflow
/// </summary>
[DataContract]
public sealed class
	GetDocumentMetaDataWorkflowDetailsCurrentWorkflow : IEquatable<GetDocumentMetaDataWorkflowDetailsCurrentWorkflow>
{
	/// <summary>
	///     Initializes a new instance of the <see cref="GetDocumentMetaDataWorkflowDetailsCurrentWorkflow" /> class.
	/// </summary>
	/// <param name="name">Workflow.</param>
	/// <param name="id">Prim Unique ID.</param>
	public GetDocumentMetaDataWorkflowDetailsCurrentWorkflow(string name = default, int? id = default)
	{
		Name = name;
		Id = id;
	}

	/// <summary>
	///     Workflow
	/// </summary>
	/// <value>Workflow</value>
	[DataMember(Name = "name", EmitDefaultValue = false)]
	public string Name { get; set; }

	/// <summary>
	///     Prim Unique ID
	/// </summary>
	/// <value>Prim Unique ID</value>
	[DataMember(Name = "id", EmitDefaultValue = false)]
	public int? Id { get; set; }

	/// <summary>
	///     Returns true if GetDocumentMetaDataWorkflowDetailsCurrentWorkflow instances are equal
	/// </summary>
	/// <param name="input">Instance of GetDocumentMetaDataWorkflowDetailsCurrentWorkflow to be compared</param>
	/// <returns>Boolean</returns>
	public bool Equals(GetDocumentMetaDataWorkflowDetailsCurrentWorkflow input)
	{
		if (input == null)
		{
			return false;
		}

		return
			(
				Name == input.Name ||
				(Name != null &&
				 Name.Equals(input.Name))
			) &&
			(
				Id == input.Id ||
				(Id != null &&
				 Id.Equals(input.Id))
			);
	}

	/// <summary>
	///     Returns the string presentation of the object
	/// </summary>
	/// <returns>String presentation of the object</returns>
	public override string ToString()
	{
		var sb = new StringBuilder();
		sb.Append("class GetDocumentMetaDataWorkflowDetailsCurrentWorkflow {\n");
		sb.Append("  Name: ").Append(Name).Append("\n");
		sb.Append("  Id: ").Append(Id).Append("\n");
		sb.Append("}\n");
		return sb.ToString();
	}

	/// <summary>
	///     Returns the JSON string presentation of the object
	/// </summary>
	/// <returns>JSON string presentation of the object</returns>
	public string ToJson()
	{
		return JsonConvert.SerializeObject(this, Formatting.Indented);
	}

	/// <summary>
	///     Returns true if objects are equal
	/// </summary>
	/// <param name="input">Object to be compared</param>
	/// <returns>Boolean</returns>
	public override bool Equals(object input)
	{
		return Equals(input as GetDocumentMetaDataWorkflowDetailsCurrentWorkflow);
	}

	/// <summary>
	///     Gets the hash code
	/// </summary>
	/// <returns>Hash code</returns>
	public override int GetHashCode()
	{
		unchecked // Overflow is fine, just wrap
		{
			int hashCode = 41;
			if (Name != null)
			{
				hashCode = hashCode * 59 + Name.GetHashCode();
			}

			if (Id != null)
			{
				hashCode = hashCode * 59 + Id.GetHashCode();
			}

			return hashCode;
		}
	}
}
