/*
 * GetMyInvoices API Documentation
 *
 * Documentation for GetMyInvoices API endpoints.
 *
 * OpenAPI spec version: v3
 * Contact: support@getmyinvoices.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Minicon.GetMyInvoices.Client.Model;

/// <summary>
///     GetDocument
/// </summary>
[DataContract]
public sealed class GetDocument : IEquatable<GetDocument>
{
	/// <summary>
	///     Initializes a new instance of the <see cref="GetDocument" /> class.
	/// </summary>
	/// <param name="metaData">metaData.</param>
	/// <param name="fileContent">File Content.</param>
	/// <param name="readableContent">Readable Content.</param>
	public GetDocument(GetDocumentMetaData metaData = default, string fileContent = default,
		string readableContent = default)
	{
		MetaData = metaData;
		FileContent = fileContent;
		ReadableContent = readableContent;
	}

	/// <summary>
	///     Gets or Sets MetaData
	/// </summary>
	[DataMember(Name = "meta_data", EmitDefaultValue = false)]
	public GetDocumentMetaData MetaData { get; set; }

	/// <summary>
	///     File Content
	/// </summary>
	/// <value>File Content</value>
	[DataMember(Name = "fileContent", EmitDefaultValue = false)]
	public string? FileContent { get; set; }

	/// <summary>
	///     Readable Content
	/// </summary>
	/// <value>Readable Content</value>
	[DataMember(Name = "readableContent", EmitDefaultValue = false)]
	public string ReadableContent { get; set; }

	/// <summary>
	///     Returns true if GetDocument instances are equal
	/// </summary>
	/// <param name="input">Instance of GetDocument to be compared</param>
	/// <returns>Boolean</returns>
	public bool Equals(GetDocument input)
	{
		if (input == null)
		{
			return false;
		}

		return
			(
				MetaData == input.MetaData ||
				(MetaData != null &&
				 MetaData.Equals(input.MetaData))
			) &&
			(
				FileContent == input.FileContent ||
				(FileContent != null &&
				 FileContent.Equals(input.FileContent))
			) &&
			(
				ReadableContent == input.ReadableContent ||
				(ReadableContent != null &&
				 ReadableContent.Equals(input.ReadableContent))
			);
	}

	/// <summary>
	///     Returns the string presentation of the object
	/// </summary>
	/// <returns>String presentation of the object</returns>
	public override string ToString()
	{
		var sb = new StringBuilder();
		sb.Append("class GetDocument {\n");
		sb.Append("  MetaData: ").Append(MetaData).Append("\n");
		sb.Append("  FileContent: ").Append(FileContent).Append("\n");
		sb.Append("  ReadableContent: ").Append(ReadableContent).Append("\n");
		sb.Append("}\n");
		return sb.ToString();
	}

	/// <summary>
	///     Returns the JSON string presentation of the object
	/// </summary>
	/// <returns>JSON string presentation of the object</returns>
	public string ToJson()
	{
		return JsonConvert.SerializeObject(this, Formatting.Indented);
	}

	/// <summary>
	///     Returns true if objects are equal
	/// </summary>
	/// <param name="input">Object to be compared</param>
	/// <returns>Boolean</returns>
	public override bool Equals(object input)
	{
		return Equals(input as GetDocument);
	}

	/// <summary>
	///     Gets the hash code
	/// </summary>
	/// <returns>Hash code</returns>
	public override int GetHashCode()
	{
		unchecked // Overflow is fine, just wrap
		{
			int hashCode = 41;
			if (MetaData != null)
			{
				hashCode = hashCode * 59 + MetaData.GetHashCode();
			}

			if (FileContent != null)
			{
				hashCode = hashCode * 59 + FileContent.GetHashCode();
			}

			if (ReadableContent != null)
			{
				hashCode = hashCode * 59 + ReadableContent.GetHashCode();
			}

			return hashCode;
		}
	}
}
