/* 
 * GetMyInvoices API Documentation
 *
 * Documentation for GetMyInvoices API endpoints.
 *
 * OpenAPI spec version: v3
 * Contact: support@getmyinvoices.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Minicon.GetMyInvoices.Client.Model;

/// <summary>
///     GetDocumentMetaDataWorkflowDetailsCurrentWorkflowStep
/// </summary>
[DataContract]
public sealed class
	GetDocumentMetaDataWorkflowDetailsCurrentWorkflowStep : IEquatable<
		GetDocumentMetaDataWorkflowDetailsCurrentWorkflowStep>
{
	/// <summary>
	///     Initializes a new instance of the <see cref="GetDocumentMetaDataWorkflowDetailsCurrentWorkflowStep" /> class.
	/// </summary>
	/// <param name="name">Workflow Step.</param>
	/// <param name="id">Prim Unique ID.</param>
	public GetDocumentMetaDataWorkflowDetailsCurrentWorkflowStep(string name = default, int? id = default)
	{
		Name = name;
		Id = id;
	}

	/// <summary>
	///     Workflow Step
	/// </summary>
	/// <value>Workflow Step</value>
	[DataMember(Name = "name", EmitDefaultValue = false)]
	public string Name { get; set; }

	/// <summary>
	///     Prim Unique ID
	/// </summary>
	/// <value>Prim Unique ID</value>
	[DataMember(Name = "id", EmitDefaultValue = false)]
	public int? Id { get; set; }

	/// <summary>
	///     Returns true if GetDocumentMetaDataWorkflowDetailsCurrentWorkflowStep instances are equal
	/// </summary>
	/// <param name="input">Instance of GetDocumentMetaDataWorkflowDetailsCurrentWorkflowStep to be compared</param>
	/// <returns>Boolean</returns>
	public bool Equals(GetDocumentMetaDataWorkflowDetailsCurrentWorkflowStep input)
	{
		if (input == null)
		{
			return false;
		}

		return
			(
				Name == input.Name ||
				(Name != null &&
				 Name.Equals(input.Name))
			) &&
			(
				Id == input.Id ||
				(Id != null &&
				 Id.Equals(input.Id))
			);
	}

	/// <summary>
	///     Returns the string presentation of the object
	/// </summary>
	/// <returns>String presentation of the object</returns>
	public override string ToString()
	{
		var sb = new StringBuilder();
		sb.Append("class GetDocumentMetaDataWorkflowDetailsCurrentWorkflowStep {\n");
		sb.Append("  Name: ").Append(Name).Append("\n");
		sb.Append("  Id: ").Append(Id).Append("\n");
		sb.Append("}\n");
		return sb.ToString();
	}

	/// <summary>
	///     Returns the JSON string presentation of the object
	/// </summary>
	/// <returns>JSON string presentation of the object</returns>
	public string ToJson()
	{
		return JsonConvert.SerializeObject(this, Formatting.Indented);
	}

	/// <summary>
	///     Returns true if objects are equal
	/// </summary>
	/// <param name="input">Object to be compared</param>
	/// <returns>Boolean</returns>
	public override bool Equals(object input)
	{
		return Equals(input as GetDocumentMetaDataWorkflowDetailsCurrentWorkflowStep);
	}

	/// <summary>
	///     Gets the hash code
	/// </summary>
	/// <returns>Hash code</returns>
	public override int GetHashCode()
	{
		unchecked // Overflow is fine, just wrap
		{
			int hashCode = 41;
			if (Name != null)
			{
				hashCode = hashCode * 59 + Name.GetHashCode();
			}

			if (Id != null)
			{
				hashCode = hashCode * 59 + Id.GetHashCode();
			}

			return hashCode;
		}
	}
}
