/* 
 * GetMyInvoices API Documentation
 *
 * Documentation for GetMyInvoices API endpoints.
 *
 * OpenAPI spec version: v3
 * Contact: support@getmyinvoices.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Minicon.GetMyInvoices.Client.Model;

/// <summary>
///     UpdateBankAccountBalanceMetaData
/// </summary>
[DataContract]
public sealed class UpdateBankAccountBalanceMetaData : IEquatable<UpdateBankAccountBalanceMetaData>
{
	/// <summary>
	///     Initializes a new instance of the <see cref="UpdateBankAccountBalanceMetaData" /> class.
	/// </summary>
	/// <param name="bankAccountUid">Bank Account ID.</param>
	/// <param name="balance">Bank Account Balance.</param>
	/// <param name="currencyCode">Bank Account Currency Code.</param>
	public UpdateBankAccountBalanceMetaData(int? bankAccountUid = default, decimal? balance = default,
		string currencyCode = default)
	{
		BankAccountUid = bankAccountUid;
		Balance = balance;
		CurrencyCode = currencyCode;
	}

	/// <summary>
	///     Bank Account ID
	/// </summary>
	/// <value>Bank Account ID</value>
	[DataMember(Name = "bankAccountUid", EmitDefaultValue = false)]
	public int? BankAccountUid { get; set; }

	/// <summary>
	///     Bank Account Balance
	/// </summary>
	/// <value>Bank Account Balance</value>
	[DataMember(Name = "balance", EmitDefaultValue = false)]
	public decimal? Balance { get; set; }

	/// <summary>
	///     Bank Account Currency Code
	/// </summary>
	/// <value>Bank Account Currency Code</value>
	[DataMember(Name = "currencyCode", EmitDefaultValue = false)]
	public string CurrencyCode { get; set; }

	/// <summary>
	///     Returns true if UpdateBankAccountBalanceMetaData instances are equal
	/// </summary>
	/// <param name="input">Instance of UpdateBankAccountBalanceMetaData to be compared</param>
	/// <returns>Boolean</returns>
	public bool Equals(UpdateBankAccountBalanceMetaData input)
	{
		if (input == null)
		{
			return false;
		}

		return
			(
				BankAccountUid == input.BankAccountUid ||
				(BankAccountUid != null &&
				 BankAccountUid.Equals(input.BankAccountUid))
			) &&
			(
				Balance == input.Balance ||
				(Balance != null &&
				 Balance.Equals(input.Balance))
			) &&
			(
				CurrencyCode == input.CurrencyCode ||
				(CurrencyCode != null &&
				 CurrencyCode.Equals(input.CurrencyCode))
			);
	}

	/// <summary>
	///     Returns the string presentation of the object
	/// </summary>
	/// <returns>String presentation of the object</returns>
	public override string ToString()
	{
		var sb = new StringBuilder();
		sb.Append("class UpdateBankAccountBalanceMetaData {\n");
		sb.Append("  BankAccountUid: ").Append(BankAccountUid).Append("\n");
		sb.Append("  Balance: ").Append(Balance).Append("\n");
		sb.Append("  CurrencyCode: ").Append(CurrencyCode).Append("\n");
		sb.Append("}\n");
		return sb.ToString();
	}

	/// <summary>
	///     Returns the JSON string presentation of the object
	/// </summary>
	/// <returns>JSON string presentation of the object</returns>
	public string ToJson()
	{
		return JsonConvert.SerializeObject(this, Formatting.Indented);
	}

	/// <summary>
	///     Returns true if objects are equal
	/// </summary>
	/// <param name="input">Object to be compared</param>
	/// <returns>Boolean</returns>
	public override bool Equals(object input)
	{
		return Equals(input as UpdateBankAccountBalanceMetaData);
	}

	/// <summary>
	///     Gets the hash code
	/// </summary>
	/// <returns>Hash code</returns>
	public override int GetHashCode()
	{
		unchecked // Overflow is fine, just wrap
		{
			int hashCode = 41;
			if (BankAccountUid != null)
			{
				hashCode = hashCode * 59 + BankAccountUid.GetHashCode();
			}

			if (Balance != null)
			{
				hashCode = hashCode * 59 + Balance.GetHashCode();
			}

			if (CurrencyCode != null)
			{
				hashCode = hashCode * 59 + CurrencyCode.GetHashCode();
			}

			return hashCode;
		}
	}
}
