/* 
 * GetMyInvoices API Documentation
 *
 * Documentation for GetMyInvoices API endpoints.
 *
 * OpenAPI spec version: v3
 * Contact: support@getmyinvoices.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Minicon.GetMyInvoices.Client.Model;

/// <summary>
///     UploadAttachment
/// </summary>
[DataContract]
public sealed class UploadAttachment : IEquatable<UploadAttachment>
{
	/// <summary>
	///     Initializes a new instance of the <see cref="UploadAttachment" /> class.
	/// </summary>
	/// <param name="success">success.</param>
	/// <param name="attachmentUid">Attachment Unique ID.</param>
	public UploadAttachment(bool? success = default, int? attachmentUid = default)
	{
		Success = success;
		AttachmentUid = attachmentUid;
	}

	/// <summary>
	///     success
	/// </summary>
	/// <value>success</value>
	[DataMember(Name = "success", EmitDefaultValue = false)]
	public bool? Success { get; set; }

	/// <summary>
	///     Attachment Unique ID
	/// </summary>
	/// <value>Attachment Unique ID</value>
	[DataMember(Name = "attachmentUid", EmitDefaultValue = false)]
	public int? AttachmentUid { get; set; }

	/// <summary>
	///     Returns true if UploadAttachment instances are equal
	/// </summary>
	/// <param name="input">Instance of UploadAttachment to be compared</param>
	/// <returns>Boolean</returns>
	public bool Equals(UploadAttachment input)
	{
		if (input == null)
		{
			return false;
		}

		return
			(
				Success == input.Success ||
				(Success != null &&
				 Success.Equals(input.Success))
			) &&
			(
				AttachmentUid == input.AttachmentUid ||
				(AttachmentUid != null &&
				 AttachmentUid.Equals(input.AttachmentUid))
			);
	}

	/// <summary>
	///     Returns the string presentation of the object
	/// </summary>
	/// <returns>String presentation of the object</returns>
	public override string ToString()
	{
		var sb = new StringBuilder();
		sb.Append("class UploadAttachment {\n");
		sb.Append("  Success: ").Append(Success).Append("\n");
		sb.Append("  AttachmentUid: ").Append(AttachmentUid).Append("\n");
		sb.Append("}\n");
		return sb.ToString();
	}

	/// <summary>
	///     Returns the JSON string presentation of the object
	/// </summary>
	/// <returns>JSON string presentation of the object</returns>
	public string ToJson()
	{
		return JsonConvert.SerializeObject(this, Formatting.Indented);
	}

	/// <summary>
	///     Returns true if objects are equal
	/// </summary>
	/// <param name="input">Object to be compared</param>
	/// <returns>Boolean</returns>
	public override bool Equals(object input)
	{
		return Equals(input as UploadAttachment);
	}

	/// <summary>
	///     Gets the hash code
	/// </summary>
	/// <returns>Hash code</returns>
	public override int GetHashCode()
	{
		unchecked // Overflow is fine, just wrap
		{
			int hashCode = 41;
			if (Success != null)
			{
				hashCode = hashCode * 59 + Success.GetHashCode();
			}

			if (AttachmentUid != null)
			{
				hashCode = hashCode * 59 + AttachmentUid.GetHashCode();
			}

			return hashCode;
		}
	}
}
